### ISSUE TITLE
Tarea 1

### ISSUE THREAD

**Issue by Kevinaleatorio** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Kevinaleatorio#1]
[mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Kevinaleatorio/files/10712424/mapa.mental.pdf)

**Comment by Gregorio012** [comment]
calificación 17% no contiene imágenes y diseño

**Comment by josealfredo79** [comment]
Bien hecho
